In [1]:
import python_utils.python_utils.caching as caching
import ml_stuff_run.ml_stuff_run.constants as constants
caching.init(constants.cache_folder, constants.which_hash)
%load_ext autoreload
%autoreload 2

In [2]:
from IPython.display import display_pretty, display_html
import python_utils.python_utils.basic as basic
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.colors as mpl_colors
import matplotlib.cm as cm
import pdb
import numpy as np
import scipy
#import ml_stuff.ml_stuff.hier_variational_regr as hvr
import causal_frl.causal_frl.hier_treatment_variational_regr as hvr

/Users/fultonw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Loading required package: mvtnorm

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/Users/fultonw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Loading required package: Matrix

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/Users/fultonw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Loading required package: stats4

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/Users/fultonw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Loading required package: gmm

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/Users/fultonw/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: Use

In [3]:
# random seed
np.random.seed(41)

In [4]:
# define params for simulating data
L = 3
N = 15000
d = 2
x_var = 15.0
mu = np.tile(5.0, d)
#prec_val = 100000
prec_val = 1
lambda_val = 1
delta = np.cumsum(np.ones(L))
treatment_prob = 0.4

In [5]:
# simulate the data
x_ns, y_ns, z_ns, T_ns, B_ls = hvr.simulate_data(L, N, d, x_var, mu, prec_val, lambda_val, delta, treatment_prob)

In [6]:
# define prior by specifying hyperparameters
v_0 = 1.0001
assert v_0 > d-1
T_0 = 1.0 * np.eye(d) 
c_0 = .0001 
m_0 = np.zeros(d)
alpha_0 = 1.
beta_0 = 1.
r_0 = -1000
s_0 = 1000

In [7]:
# define params for doing inference
num_iters = 5

In [8]:
# initialize params
v, T, c, m, mu_B_ls, prec_B_ls, alpha_lambda_ls, beta_lambda_ls, mu_delta, prec_delta = hvr.init_variational_params\
(x_ns, y_ns, z_ns, T_ns, v_0, T_0, c_0, m_0, alpha_0, beta_0, r_0, s_0)

In [9]:
# do inference
v, T, c, m, mu_B_ls, prec_B_ls, alpha_lambda_ls, beta_lambda_ls, mu_delta, prec_delta = hvr.infer_variational_params(num_iters, x_ns, y_ns, z_ns, T_ns, v_0, T_0, c_0, m_0, alpha_0, beta_0, r_0, s_0,\
                         v, T, c, m, mu_B_ls, prec_B_ls, alpha_lambda_ls, beta_lambda_ls, mu_delta, prec_delta)

L: 3 d: 2
0 0.0
first [ 1.  1.  1.] second [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
ddt [ 1.  1.  1.] [[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]
squared error 0 5442719.14167 7256.68826444 11.1173987402 0.0 -25.12
gg [ 0.  0.  0.  0.  0.] [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] [[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]
squared error 1 2593394.51679 -49848.9333542 172.479158408 0.0 -76.29
gg [ 0.  0.  0.  0.  0.] [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] [[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]
squared error 2 4233143.64875 -158841.533223 459.68271476 0.0 -153.18
gg [ 0.  0.  0.  0.  0.] [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] [[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]
asdf -130125.754297 [ 1.  1.  1.] [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
delta entropy 4.25681559961
1 step 0 mu_B_ls sum: 0.000 log evidence bound: -130151.010521
[ 1.  1.  1.]
first [ 0.44257161  2.948682    2.61

In [10]:
print 'v',v
print 'T', T
print 'c', c
print 'm', m
print 'mu_B_ls', mu_B_ls
print 'prec_B_ls', prec_B_ls
print 'alpha_lambda_ls', alpha_lambda_ls
print 'beta_lambda_ls', beta_lambda_ls
print y_ns

v 4.0001
T [[ 0.37936884 -0.04680091]
 [-0.04680091  0.18907812]]
c 3.0001
m [ 4.9120277   5.31388855]
mu_B_ls [[ 5.95569617  6.08957641]
 [ 4.59439009  3.59393843]
 [ 4.18648804  6.25868219]]
prec_B_ls [array([[ 73456.18765539,   -228.99188226],
       [  -228.99188226,  77120.40009566]]), array([[ 151981.73103309,    1510.79560855],
       [   1510.79560855,  151748.81179483]]), array([[ 224184.19833784,   -6302.65849163],
       [  -6302.65849163,  222805.17738396]])]
alpha_lambda_ls [ 2501.  2501.  2501.]
beta_lambda_ls [ 2495.9175528   1239.67469689   853.88268069]
[ -3.98331442  -7.25996425 -10.46927572 ..., -22.76889796 -54.50764536
 -38.99906205]


In [11]:
print np.mean(np.abs(mu_B_ls - B_ls))
print 'estimated', v*T
print 'actual empirical', 1.0/np.var(mu_B_ls[:,0])
print mu_B_ls
print np.concatenate([mu_B_ls,B_ls],axis=1)
print prec_B_ls
print 'lambdas', alpha_lambda_ls / beta_lambda_ls
print mu_delta
print prec_delta

0.0021737750472
estimated [[ 1.51751328 -0.18720832]
 [-0.18720832  0.7563314 ]]
actual empirical 1.74769643806
[[ 5.95569617  6.08957641]
 [ 4.59439009  3.59393843]
 [ 4.18648804  6.25868219]]
[[ 5.95569617  6.08957641  5.95578111  6.0922468 ]
 [ 4.59439009  3.59393843  4.5931437   3.59793486]
 [ 4.18648804  6.25868219  4.18516598  6.26240461]]
[array([[ 73456.18765539,   -228.99188226],
       [  -228.99188226,  77120.40009566]]), array([[ 151981.73103309,    1510.79560855],
       [   1510.79560855,  151748.81179483]]), array([[ 224184.19833784,   -6302.65849163],
       [  -6302.65849163,  222805.17738396]])]
lambdas [ 1.0020363   2.01746475  2.9289738 ]
[ 0.96463652  2.02507468  3.01547587]
[[ 15125.1981546   12608.08295875   7477.67010581]
 [ 12608.08295875  12608.08295875   7477.67010581]
 [  7477.67010581   7477.67010581   7477.67010581]]


In [12]:
h=hvr.trunc_norm()
h.mean(np.array([0,0,0]),np.array([[2,1,1],[1,2,1],[1,1,2]]))

array([ 0.,  0.,  0.])