In [1]:
import constants
cache_folder_name = 'test'
seed = 44

In [2]:
import autograd.numpy as np
np.random.seed(seed)
import python_utils.python_utils.basic as basic
import python_utils.python_utils.caching as caching
log_folder = '%s/%s' % (constants.cache_folder, cache_folder_name)
caching.init(constants.cache_folder, constants.which_hash, basic.archiver(log_folder))
%load_ext autoreload
%autoreload 2
import matplotlib
matplotlib.use('Agg')

[Errno 17] File exists: '/Users/fultonw/Documents/projects/runs/domain_adapt_run/domain_adapt_run/notebooks/new/cross_validation/cache/test'


In [3]:
import matplotlib.pyplot as plt
from IPython.display import display_pretty, display_html
import python_utils.python_utils.basic as basic
import pandas as pd
import pdb
import itertools
import functools
import scipy.stats
import scipy
import cvxopt
import autograd
import autograd.numpy as np
import domain_adapt.domain_adapt.new.fxns as fxns
import domain_adapt.domain_adapt.new.utils as utils
import domain_adapt.domain_adapt.new.optimizers as optimizers
import domain_adapt.domain_adapt.new.constructors as constructors
import domain_adapt.domain_adapt.new.lsif_constructor as lsif_constructor
import domain_adapt.domain_adapt.new.cv as cv
#import domain_adapt.domain_adapt.SDR_data as data
import domain_adapt_run.domain_adapt_run.notebooks.new.cross_validation.run as run
import data.domain_adapt_data.domain_adapt_data.fxns as data

Couldn't import dot_parser, loading of dot files will not be possible.


In [4]:
# define 
def random_data_getter(seed):
    xs, ys = data.kin_data('kin-32fh')
    N_train = 100
    N_test = 500
    c_cols=range(8)
    return data.lsif_data_subsample(xs, ys, N_train, N_test, seed=seed, c_cols=c_cols)

In [5]:
# define
cv_which_loss = 'square'
cv_num_folds = 3
#cv_num_folds = 2
cv_use_test = False
predictor_which_loss = 'square'
num_basis = 100
u_dim = 8
pymanopt_options={'logverbosity':1, 'maxiter':10}
many_optimizer_num_cycles = 3
num_tries = 2
B_init_f_getter = lambda xs_train, ys_train, xs_test: (lambda: np.random.normal(size=(xs_train.shape[1],u_dim)))
tradeoff_weight_regs = 2**np.linspace(-3,3,7)
#tradeoff_weight_regs = 2**np.linspace(-1,1,3)
fitter_list = [lsif_constructor.lsif_ratio_fitter(predictor_which_loss, num_basis, tradeoff_weight_reg, B_init_f_getter, num_tries=num_tries, pymanopt_options=pymanopt_options, many_optimizer_num_cycles=many_optimizer_num_cycles) for tradeoff_weight_reg in tradeoff_weight_regs]
fitter = cv.cv_fitter(fitter_list, cv_which_loss, cv_num_folds, cv_use_test)

In [6]:
# run
eval_num_trials = 100
eval_which_loss = 'square'
eval_num_folds = 0
eval_use_test = True
run.run(random_data_getter, eval_num_trials, eval_which_loss, eval_num_folds, eval_use_test, fitter)

/Users/fultonw/Documents/projects/code/data/domain_adapt_data/data/kin-32fh.data
try 0
100000 100000
c_lsif, sigma
[ 1.99892675  2.1303608   2.22072001] sigma_range
(0.01, 1.9989267519610556) -0.338341474394 best
c_pred
B
Terminated - max iterations reached after 0.49 seconds.

0.01 1.99892675196
c_lsif, sigma
[ 0.38238429  0.41011467  0.44393334] sigma_range
(0.10000000000000001, 0.44393333990254191) -0.249252322599 best
c_pred
B
Terminated - max iterations reached after 0.53 seconds.

0.1 0.443933339903
c_lsif, sigma
[ 0.4627159   0.4990508   0.51862753] sigma_range
(0.10000000000000001, 0.49905080261533186) -0.34944857729 best
c_pred
B
Terminated - max iterations reached after 0.49 seconds.

try 1
100000 100000
c_lsif, sigma
[ 2.81793456  3.10496593  3.18152712] sigma_range
(0.10000000000000001, 3.1815271185120659) -0.458748281339 best
c_pred
B
Terminated - max iterations reached after 0.52 seconds.

0.1 3.18152711851
c_lsif, sigma
[ 0.47808475  0.48458742  0.51131459] sigma_range
(

KeyboardInterrupt: 